# Site settings
title: Cosme 
email: jcosmexavier@gmail.com
url: https://josecosme.github.io
description: "Analise e manutenão de redes eletricas, Analise de Quadro Bifásico - Trifásico, colocação de pisos"
skills: "Eletrica - Pisos - Analise de Quadro Bifásico - Trifásico"
meta_author: Cosme José

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Eletro Cosme MEI CNPJ 22.293.496/0001-71    - 
  location: Endereço
  social: Facebook
  credits: Telefones

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/jose.cosme.1293


# Postal address (add as many lines as necessary)
address:
  - line: Alameda Governador Mario Covas, Nº 01, Parque São Joaquim
  - line: Taboão da Serra - SP
# Credits content
credits: '(WhatsApp) Vivo : (11) 96394-1656 - Tim : (11) 98160-6235'

# Build settings
markdown: kramdown
permalink: pretty
